### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by TrueCitrus** [1activegeek/docker-airconnect#5] opened 2019-10-03 02:42 UTC
I just created a container on my QNAP TS-451+ and it seems to be working fine as I can see all my Sonos speakers however I don’t hear any audio output when choosing a speaker. I didn’t specify airupnp or anything but it seems like it’s running based on the output of the container.  Do I need to specify the latency for Sonos?

I’m not sure if it means anything but the Sonos speakers show up with a + at the end of the name.

**Comment by 1activegeek** [comment] 2019-10-03 03:24
Please refer to the documentation for the software by the creator. The container has been validated  as functioning as intended for thousands of users. It is likely you need to setup something in the configuration. Unfortunately I'm not versed in configurations for specific devices. In my home it just automatically discovers my chrome cast devices. Sonos may be different and there are various notes in the creators readme. 

Closing as I don't provide support for the code.

**Closed by 1activegeek** 2019-10-03 03:24 UTC

**Comment by TrueCitrus** [comment] 2019-10-03 04:20
I apologize as this the first time I have ever ran a container before. I have followed the software documentation and placed a config.xml file in the same directory as the airupnp executable in the bin folder however the docker container doesnt seem to read it. If I launch airupnp manually from the docker terminal it is reading the config.xml file correctly. How can I get the docker container to read the config.xml file automatically?

**Comment by 1activegeek** [comment] 2019-10-03 05:34
If you need to have a file read inside the container, you will need to either use a volume mounted to the container or bind mount a local directory to the container. I'd suggest digging into docker documentation to understand what you're doing a bit better. A simple way to bind mount a local config.xml:
`docker run -d -v /local/path/on/host/config.xml:/directory/inside/container/config.xml --net=host 1activegeek/airconnect`

**Comment by TrueCitrus** [comment] 2019-10-03 23:45
I’ve already created a config file directly inside the container via console. According to the software documentation AirConnect should automatically use the config.xml if it’s located in the same directory as the executable. I’ve already confirmed the config file works because if I start the airconnect process manually in the container it works correctly. 
 
Using your example above where would I put in the environment variable AIRUPNP_VAR? Or if I don’t specify will settings apply to both executables?

Thanks again for your help.

**Comment by 1activegeek** [comment] 2019-10-04 01:18
You really need to do some reading on docker. You're basically asking me to build a customer docker run command for your specific situation. `-e` allows you to set environment variables. And as I've documented in the readme, AIRUPNP_VAR will apply to the airupnp runtime.

**Comment by TrueCitrus** [comment] 2019-10-04 04:12
Thanks for your help. I am reading the Docker documentation to better understand how run commands work. 

The only thing I am trying to figure out is why the container isn’t already reading the config file if it’s already in the default location. The runtime commands listed for this container say the default is ./config.xml which is where my config file is located. 

I apologize for all the confusion as this is all new to me. I appreciate your patience.
